authorName: default
experimentName: cifar_adl
trialConcurrency: 1
maxExecDuration: 3h
maxTrialNum: 10
nniManagerIp: 10.20.100.199
trainingServicePlatform: adl
searchSpacePath: search_space_demo.json
logCollection: http
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
trial:
  command: python3 /cifar10/main_nni.py
  codeDir: .
  gpuNum: 1
  image: registry.petuum.com/dev/nni:cifar-example
  imagePullSecrets:
    - name: stagingsecret
  adaptive: true
  checkpoint:
    storageClass: dfs
    storageSize: 1Gi
  cpuNum: 1
  memorySize: 1Gi
